ansible_default_paths:
  inventory: /home/prelersc/workspace/wolfden/ansible_enviornments
  playbook: /home/prelersc/workspace/wolfden/ansible_playbooks
  config: /home/prelersc/workspace/wolfden/ansible.cfg